#! /bin/sh


user_name="$(git config --global user.name)"
case $user_name in
    Travis\ *|GitHub\ Actions|"")
        git config --global --unset user.name
        git config --global --unset user.email
        ;;
    *)
        echo >&2 "Can not work with '$user_name'."
        exit 77 ;;
esac

. "$(dirname "$0")/test-lib.sh"
test_start

repos_ff_ready

( set +e
git-mirror \
    --source "$(pwd)/origin.git" \
    --destination "$(pwd)/fork.git" \
    --cache-dir "$(pwd)/cache" \
    --branch main \
    --branch new_branch 2>&1 | grep 'no global user.name'
)

git-mirror \
    --source "$(pwd)/origin.git" \
    --destination "$(pwd)/fork.git" \
    --cache-dir "$(pwd)/cache" \
    --branch main \
    --branch new_branch \
    --user-name 'John Doe' \
    --user-mail 'john@doe.org'
