#! /bin/sh

. "$(dirname "$0")/test-lib.sh"
test_start

repos_ff_ready

assert_log_length fork.git main 1
assert_log_length fork.git new_branch 2

git-mirror \
    --source "$(pwd)/origin.git" \
    --destination "$(pwd)/fork.git" \
    --cache-dir "$(pwd)/cache" \
    --branch main \
    --branch new_branch

assert_log_length fork.git main 2
assert_log_length fork.git new_branch 3

git-mirror \
    --source "$(pwd)/origin.git" \
    --destination "$(pwd)/fork.git" \
    --cache-dir "$(pwd)/cache" \
    --branch main \
    --branch new_branch

assert_log_length fork.git main 2
assert_log_length fork.git new_branch 3

(
    cd source
    our_git checkout main
    touch file
    our_git add file
    our_git commit -m "third commit"
    our_git push --all
)

git-mirror \
    --source "$(pwd)/origin.git" \
    --destination "$(pwd)/fork.git" \
    --cache-dir "$(pwd)/cache" \
    --branch main \
    --branch new_branch

assert_log_length fork.git main 3
assert_log_length fork.git new_branch 3
